/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ChainlinkETHToETHOracle } from "../ChainlinkETHToETHOracle";

export class ChainlinkETHToETHOracle__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ChainlinkETHToETHOracle> {
    return super.deploy(overrides || {}) as Promise<ChainlinkETHToETHOracle>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainlinkETHToETHOracle {
    return super.attach(address) as ChainlinkETHToETHOracle;
  }
  connect(signer: Signer): ChainlinkETHToETHOracle__factory {
    return super.connect(signer) as ChainlinkETHToETHOracle__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainlinkETHToETHOracle {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ChainlinkETHToETHOracle;
  }
}

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060948061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806350d25bcd1460375780638205bf6a14604f575b600080fd5b603d6055565b60408051918252519081900360200190f35b603d605a565b600190565b429056fea2646970667358221220ec524fe34e153e1dbd149fe1621c93c231c6e3df95caeeeca087459ebb5ad05664736f6c634300060c0033";
