/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ChainlinkETHToETHOracle } from "../ChainlinkETHToETHOracle";

export class ChainlinkETHToETHOracle__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ChainlinkETHToETHOracle> {
    return super.deploy(overrides || {}) as Promise<ChainlinkETHToETHOracle>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainlinkETHToETHOracle {
    return super.attach(address) as ChainlinkETHToETHOracle;
  }
  connect(signer: Signer): ChainlinkETHToETHOracle__factory {
    return super.connect(signer) as ChainlinkETHToETHOracle__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainlinkETHToETHOracle {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ChainlinkETHToETHOracle;
  }
}

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b68061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806350d25bcd1460375780638205bf6a146053575b600080fd5b603d606f565b6040518082815260200191505060405180910390f35b60596078565b6040518082815260200191505060405180910390f35b60006001905090565b60004290509056fea2646970667358221220a5152170d6cd03cfb4519926096f777e9bc8c18d7287528d6fdf8e78f18b943f64736f6c634300060c0033";
