/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ConverterV28OrHigherWithFallback } from "../ConverterV28OrHigherWithFallback";

export class ConverterV28OrHigherWithFallback__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ConverterV28OrHigherWithFallback> {
    return super.deploy(
      overrides || {}
    ) as Promise<ConverterV28OrHigherWithFallback>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ConverterV28OrHigherWithFallback {
    return super.attach(address) as ConverterV28OrHigherWithFallback;
  }
  connect(signer: Signer): ConverterV28OrHigherWithFallback__factory {
    return super.connect(signer) as ConverterV28OrHigherWithFallback__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConverterV28OrHigherWithFallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ConverterV28OrHigherWithFallback;
  }
}

const _abi = [
  {
    inputs: [],
    name: "isV28OrHigher",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50608e8061001e6000396000f3fe608060405260043610601f5760003560e01c8063d260529c14602d576028565b36602857600080fd5b600080fd5b348015603857600080fd5b50603f6053565b604080519115158252519081900360200190f35b60019056fea26469706673582212208fa8f13606d433d3cd98204df9c736b32c0655a95c32da062d53920e10345b7d64736f6c634300060c0033";
