/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChainlinkPriceOracle } from "../IChainlinkPriceOracle";

export class IChainlinkPriceOracle__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkPriceOracle {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainlinkPriceOracle;
  }
}

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
