/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITypedConverterCustomFactory } from "../ITypedConverterCustomFactory";

export class ITypedConverterCustomFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITypedConverterCustomFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITypedConverterCustomFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "converterType",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
