version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
        name: Run Tests
        command: yarn test

workflows:
  version: 2
  run_tests:
    jobs:
      - test

