/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IBancorFormulaInterface extends ethers.utils.Interface {
  functions: {
    "balancedWeights(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)": FunctionFragment;
    "fundCost(uint256,uint256,uint32,uint256)": FunctionFragment;
    "fundSupplyAmount(uint256,uint256,uint32,uint256)": FunctionFragment;
    "liquidateReserveAmount(uint256,uint256,uint32,uint256)": FunctionFragment;
    "purchaseTargetAmount(uint256,uint256,uint32,uint256)": FunctionFragment;
    "saleTargetAmount(uint256,uint256,uint32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "balancedWeights",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "crossReserveTargetAmount",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fundCost",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundSupplyAmount",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateReserveAmount",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTargetAmount",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "saleTargetAmount",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "balancedWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossReserveTargetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundSupplyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateReserveAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTargetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleTargetAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export class IBancorFormula extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IBancorFormulaInterface;

  functions: {
    balancedWeights(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    "balancedWeights(uint256,uint256,uint256,uint256,uint256)"(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    crossReserveTargetAmount(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)"(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fundCost(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "fundCost(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fundSupplyAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "fundSupplyAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    liquidateReserveAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "liquidateReserveAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    purchaseTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "purchaseTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    saleTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "saleTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  balancedWeights(
    _primaryReserveStakedBalance: BigNumberish,
    _primaryReserveBalance: BigNumberish,
    _secondaryReserveBalance: BigNumberish,
    _reserveRateNumerator: BigNumberish,
    _reserveRateDenominator: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[number, number]>;

  "balancedWeights(uint256,uint256,uint256,uint256,uint256)"(
    _primaryReserveStakedBalance: BigNumberish,
    _primaryReserveBalance: BigNumberish,
    _secondaryReserveBalance: BigNumberish,
    _reserveRateNumerator: BigNumberish,
    _reserveRateDenominator: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[number, number]>;

  crossReserveTargetAmount(
    _sourceReserveBalance: BigNumberish,
    _sourceReserveWeight: BigNumberish,
    _targetReserveBalance: BigNumberish,
    _targetReserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)"(
    _sourceReserveBalance: BigNumberish,
    _sourceReserveWeight: BigNumberish,
    _targetReserveBalance: BigNumberish,
    _targetReserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fundCost(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "fundCost(uint256,uint256,uint32,uint256)"(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fundSupplyAmount(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "fundSupplyAmount(uint256,uint256,uint32,uint256)"(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  liquidateReserveAmount(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "liquidateReserveAmount(uint256,uint256,uint32,uint256)"(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveRatio: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  purchaseTargetAmount(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "purchaseTargetAmount(uint256,uint256,uint32,uint256)"(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  saleTargetAmount(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "saleTargetAmount(uint256,uint256,uint32,uint256)"(
    _supply: BigNumberish,
    _reserveBalance: BigNumberish,
    _reserveWeight: BigNumberish,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    balancedWeights(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    "balancedWeights(uint256,uint256,uint256,uint256,uint256)"(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    crossReserveTargetAmount(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)"(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fundCost(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fundCost(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fundSupplyAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fundSupplyAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateReserveAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "liquidateReserveAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchaseTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "purchaseTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    saleTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "saleTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    balancedWeights(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balancedWeights(uint256,uint256,uint256,uint256,uint256)"(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    crossReserveTargetAmount(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)"(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fundCost(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fundCost(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fundSupplyAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fundSupplyAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateReserveAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "liquidateReserveAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchaseTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "purchaseTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    saleTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "saleTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balancedWeights(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balancedWeights(uint256,uint256,uint256,uint256,uint256)"(
      _primaryReserveStakedBalance: BigNumberish,
      _primaryReserveBalance: BigNumberish,
      _secondaryReserveBalance: BigNumberish,
      _reserveRateNumerator: BigNumberish,
      _reserveRateDenominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    crossReserveTargetAmount(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "crossReserveTargetAmount(uint256,uint32,uint256,uint32,uint256)"(
      _sourceReserveBalance: BigNumberish,
      _sourceReserveWeight: BigNumberish,
      _targetReserveBalance: BigNumberish,
      _targetReserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fundCost(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fundCost(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fundSupplyAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fundSupplyAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidateReserveAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "liquidateReserveAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveRatio: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    purchaseTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "purchaseTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    saleTargetAmount(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "saleTargetAmount(uint256,uint256,uint32,uint256)"(
      _supply: BigNumberish,
      _reserveBalance: BigNumberish,
      _reserveWeight: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
