/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IBancorRegistryInterface extends ethers.utils.Interface {
  functions: {
    "addressOf(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressOf",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addressOf", data: BytesLike): Result;

  events: {};
}

export class IBancorRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IBancorRegistryInterface;

  functions: {
    addressOf(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "addressOf(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addressOf(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "addressOf(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addressOf(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "addressOf(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addressOf(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "addressOf(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressOf(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressOf(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
