/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface XTransferRerouterInterface extends ethers.utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "enableRerouting(bool)": FunctionFragment;
    "newOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "rerouteTx(uint256,bytes32,bytes32)": FunctionFragment;
    "reroutingEnabled()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableRerouting",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "newOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rerouteTx",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reroutingEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableRerouting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rerouteTx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reroutingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnerUpdate(address,address)": EventFragment;
    "TxReroute(uint256,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnerUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TxReroute"): EventFragment;
}

export class XTransferRerouter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: XTransferRerouterInterface;

  functions: {
    acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    enableRerouting(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "enableRerouting(bool)"(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    newOwner(overrides?: CallOverrides): Promise<[string]>;

    "newOwner()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    rerouteTx(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "rerouteTx(uint256,bytes32,bytes32)"(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    reroutingEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    "reroutingEnabled()"(overrides?: CallOverrides): Promise<[boolean]>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  enableRerouting(
    _enable: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "enableRerouting(bool)"(
    _enable: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  newOwner(overrides?: CallOverrides): Promise<string>;

  "newOwner()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  rerouteTx(
    _txId: BigNumberish,
    _blockchain: BytesLike,
    _to: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "rerouteTx(uint256,bytes32,bytes32)"(
    _txId: BigNumberish,
    _blockchain: BytesLike,
    _to: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  reroutingEnabled(overrides?: CallOverrides): Promise<boolean>;

  "reroutingEnabled()"(overrides?: CallOverrides): Promise<boolean>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    _newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    "acceptOwnership()"(overrides?: CallOverrides): Promise<void>;

    enableRerouting(_enable: boolean, overrides?: CallOverrides): Promise<void>;

    "enableRerouting(bool)"(
      _enable: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    newOwner(overrides?: CallOverrides): Promise<string>;

    "newOwner()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    rerouteTx(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "rerouteTx(uint256,bytes32,bytes32)"(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    reroutingEnabled(overrides?: CallOverrides): Promise<boolean>;

    "reroutingEnabled()"(overrides?: CallOverrides): Promise<boolean>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnerUpdate(
      _prevOwner: string | null,
      _newOwner: string | null
    ): EventFilter;

    TxReroute(
      _txId: BigNumberish | null,
      _toBlockchain: null,
      _to: null
    ): EventFilter;
  };

  estimateGas: {
    acceptOwnership(overrides?: Overrides): Promise<BigNumber>;

    "acceptOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    enableRerouting(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "enableRerouting(bool)"(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "newOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    rerouteTx(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "rerouteTx(uint256,bytes32,bytes32)"(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    reroutingEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    "reroutingEnabled()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    enableRerouting(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "enableRerouting(bool)"(
      _enable: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    newOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rerouteTx(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "rerouteTx(uint256,bytes32,bytes32)"(
      _txId: BigNumberish,
      _blockchain: BytesLike,
      _to: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    reroutingEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "reroutingEnabled()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
