/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DynamicTokenControllerInterface extends ethers.utils.Interface {
  functions: {
    "bancorRegistry()": FunctionFragment;
    "converters(uint256)": FunctionFragment;
    "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)": FunctionFragment;
    "dsTokenImplementation()": FunctionFragment;
    "dynamicConverterImplementation()": FunctionFragment;
    "initialize(address,address,address,address,address)": FunctionFragment;
    "onSetZnsController(address,address,uint256,bytes)": FunctionFragment;
    "reduceWeight(uint256,address)": FunctionFragment;
    "reduceWeightTo(uint256,address,address)": FunctionFragment;
    "registry()": FunctionFragment;
    "setBancorRegistry(address)": FunctionFragment;
    "setDSTokenImplementation(address)": FunctionFragment;
    "setDynamicConverterImplemenation(address)": FunctionFragment;
    "stakingController()": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "upgradeConverter(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bancorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "converters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDynamicTokenAndConfigureStake",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dsTokenImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dynamicConverterImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetZnsController",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceWeight",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceWeightTo",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBancorRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDSTokenImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDynamicConverterImplemenation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeConverter",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bancorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "converters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createDynamicTokenAndConfigureStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dsTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dynamicConverterImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onSetZnsController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceWeightTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBancorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDSTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDynamicConverterImplemenation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeConverter",
    data: BytesLike
  ): Result;

  events: {
    "DynamicConverterUpgraded(uint256,address,address,address,address)": EventFragment;
    "DynamicTokenCreated(uint256,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DynamicConverterUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DynamicTokenCreated"): EventFragment;
}

export class DynamicTokenController extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DynamicTokenControllerInterface;

  functions: {
    bancorRegistry(overrides?: CallOverrides): Promise<[string]>;

    "bancorRegistry()"(overrides?: CallOverrides): Promise<[string]>;

    converters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "converters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createDynamicTokenAndConfigureStake(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)"(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    dsTokenImplementation(overrides?: CallOverrides): Promise<[string]>;

    "dsTokenImplementation()"(overrides?: CallOverrides): Promise<[string]>;

    dynamicConverterImplementation(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "dynamicConverterImplementation()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,address,address)"(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onSetZnsController(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onSetZnsController(address,address,uint256,bytes)"(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    reduceWeight(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reduceWeight(uint256,address)"(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    reduceWeightTo(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reduceWeightTo(uint256,address,address)"(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    "registry()"(overrides?: CallOverrides): Promise<[string]>;

    setBancorRegistry(
      _registry: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBancorRegistry(address)"(
      _registry: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDSTokenImplementation(
      _impl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDSTokenImplementation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDynamicConverterImplemenation(
      _impl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDynamicConverterImplemenation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    stakingController(overrides?: CallOverrides): Promise<[string]>;

    "stakingController()"(overrides?: CallOverrides): Promise<[string]>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    upgradeConverter(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeConverter(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  bancorRegistry(overrides?: CallOverrides): Promise<string>;

  "bancorRegistry()"(overrides?: CallOverrides): Promise<string>;

  converters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "converters(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  createDynamicTokenAndConfigureStake(
    id: BigNumberish,
    reserve: string,
    initWeight: BigNumberish,
    stepWeight: BigNumberish,
    minWeight: BigNumberish,
    mcapThreshold: BigNumberish,
    minBid: BigNumberish,
    name: string,
    symbol: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)"(
    id: BigNumberish,
    reserve: string,
    initWeight: BigNumberish,
    stepWeight: BigNumberish,
    minWeight: BigNumberish,
    mcapThreshold: BigNumberish,
    minBid: BigNumberish,
    name: string,
    symbol: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  dsTokenImplementation(overrides?: CallOverrides): Promise<string>;

  "dsTokenImplementation()"(overrides?: CallOverrides): Promise<string>;

  dynamicConverterImplementation(overrides?: CallOverrides): Promise<string>;

  "dynamicConverterImplementation()"(
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    _dsImpl: string,
    _dconvImpl: string,
    _stakingController: string,
    _registry: string,
    _bancorRegistry: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,address,address)"(
    _dsImpl: string,
    _dconvImpl: string,
    _stakingController: string,
    _registry: string,
    _bancorRegistry: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onSetZnsController(
    sender: string,
    oldController: string,
    id: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onSetZnsController(address,address,uint256,bytes)"(
    sender: string,
    oldController: string,
    id: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  reduceWeight(
    id: BigNumberish,
    reserveToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reduceWeight(uint256,address)"(
    id: BigNumberish,
    reserveToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  reduceWeightTo(
    id: BigNumberish,
    reserveToken: string,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reduceWeightTo(uint256,address,address)"(
    id: BigNumberish,
    reserveToken: string,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registry(overrides?: CallOverrides): Promise<string>;

  "registry()"(overrides?: CallOverrides): Promise<string>;

  setBancorRegistry(
    _registry: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBancorRegistry(address)"(
    _registry: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDSTokenImplementation(
    _impl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDSTokenImplementation(address)"(
    _impl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDynamicConverterImplemenation(
    _impl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDynamicConverterImplemenation(address)"(
    _impl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  stakingController(overrides?: CallOverrides): Promise<string>;

  "stakingController()"(overrides?: CallOverrides): Promise<string>;

  tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokens(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  upgradeConverter(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeConverter(uint256)"(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bancorRegistry(overrides?: CallOverrides): Promise<string>;

    "bancorRegistry()"(overrides?: CallOverrides): Promise<string>;

    converters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "converters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createDynamicTokenAndConfigureStake(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)"(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: CallOverrides
    ): Promise<void>;

    dsTokenImplementation(overrides?: CallOverrides): Promise<string>;

    "dsTokenImplementation()"(overrides?: CallOverrides): Promise<string>;

    dynamicConverterImplementation(overrides?: CallOverrides): Promise<string>;

    "dynamicConverterImplementation()"(
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,address,address)"(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    onSetZnsController(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onSetZnsController(address,address,uint256,bytes)"(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    reduceWeight(
      id: BigNumberish,
      reserveToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "reduceWeight(uint256,address)"(
      id: BigNumberish,
      reserveToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    reduceWeightTo(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "reduceWeightTo(uint256,address,address)"(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registry(overrides?: CallOverrides): Promise<string>;

    "registry()"(overrides?: CallOverrides): Promise<string>;

    setBancorRegistry(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBancorRegistry(address)"(
      _registry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDSTokenImplementation(
      _impl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDSTokenImplementation(address)"(
      _impl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDynamicConverterImplemenation(
      _impl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDynamicConverterImplemenation(address)"(
      _impl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stakingController(overrides?: CallOverrides): Promise<string>;

    "stakingController()"(overrides?: CallOverrides): Promise<string>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    upgradeConverter(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeConverter(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    DynamicConverterUpgraded(
      id: BigNumberish | null,
      reserve: string | null,
      dsToken: string | null,
      oldConverter: null,
      newConverter: null
    ): EventFilter;

    DynamicTokenCreated(
      id: BigNumberish | null,
      reserve: string | null,
      dsToken: null,
      converter: null
    ): EventFilter;
  };

  estimateGas: {
    bancorRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    "bancorRegistry()"(overrides?: CallOverrides): Promise<BigNumber>;

    converters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "converters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createDynamicTokenAndConfigureStake(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)"(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    dsTokenImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    "dsTokenImplementation()"(overrides?: CallOverrides): Promise<BigNumber>;

    dynamicConverterImplementation(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "dynamicConverterImplementation()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,address,address,address)"(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onSetZnsController(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onSetZnsController(address,address,uint256,bytes)"(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    reduceWeight(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reduceWeight(uint256,address)"(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    reduceWeightTo(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reduceWeightTo(uint256,address,address)"(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    "registry()"(overrides?: CallOverrides): Promise<BigNumber>;

    setBancorRegistry(
      _registry: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setBancorRegistry(address)"(
      _registry: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDSTokenImplementation(
      _impl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDSTokenImplementation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDynamicConverterImplemenation(
      _impl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDynamicConverterImplemenation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    stakingController(overrides?: CallOverrides): Promise<BigNumber>;

    "stakingController()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeConverter(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeConverter(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bancorRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bancorRegistry()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    converters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "converters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createDynamicTokenAndConfigureStake(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createDynamicTokenAndConfigureStake(uint256,address,uint32,uint32,uint32,uint256,uint256,string,string)"(
      id: BigNumberish,
      reserve: string,
      initWeight: BigNumberish,
      stepWeight: BigNumberish,
      minWeight: BigNumberish,
      mcapThreshold: BigNumberish,
      minBid: BigNumberish,
      name: string,
      symbol: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    dsTokenImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "dsTokenImplementation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dynamicConverterImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "dynamicConverterImplementation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,address,address)"(
      _dsImpl: string,
      _dconvImpl: string,
      _stakingController: string,
      _registry: string,
      _bancorRegistry: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onSetZnsController(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onSetZnsController(address,address,uint256,bytes)"(
      sender: string,
      oldController: string,
      id: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    reduceWeight(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reduceWeight(uint256,address)"(
      id: BigNumberish,
      reserveToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    reduceWeightTo(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reduceWeightTo(uint256,address,address)"(
      id: BigNumberish,
      reserveToken: string,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "registry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBancorRegistry(
      _registry: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBancorRegistry(address)"(
      _registry: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDSTokenImplementation(
      _impl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDSTokenImplementation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDynamicConverterImplemenation(
      _impl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDynamicConverterImplemenation(address)"(
      _impl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    stakingController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "stakingController()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeConverter(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeConverter(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
