/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LiquidityPoolV2ConverterAnchorFactoryInterface
  extends ethers.utils.Interface {
  functions: {
    "converterType()": FunctionFragment;
    "createAnchor(string,string,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "converterType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAnchor",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "converterType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAnchor",
    data: BytesLike
  ): Result;

  events: {};
}

export class LiquidityPoolV2ConverterAnchorFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LiquidityPoolV2ConverterAnchorFactoryInterface;

  functions: {
    converterType(overrides?: CallOverrides): Promise<[number]>;

    "converterType()"(overrides?: CallOverrides): Promise<[number]>;

    createAnchor(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createAnchor(string,string,uint8)"(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  converterType(overrides?: CallOverrides): Promise<number>;

  "converterType()"(overrides?: CallOverrides): Promise<number>;

  createAnchor(
    _name: string,
    _symbol: string,
    _decimals: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createAnchor(string,string,uint8)"(
    _name: string,
    _symbol: string,
    _decimals: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    converterType(overrides?: CallOverrides): Promise<number>;

    "converterType()"(overrides?: CallOverrides): Promise<number>;

    createAnchor(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "createAnchor(string,string,uint8)"(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    converterType(overrides?: CallOverrides): Promise<BigNumber>;

    "converterType()"(overrides?: CallOverrides): Promise<BigNumber>;

    createAnchor(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createAnchor(string,string,uint8)"(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    converterType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "converterType()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createAnchor(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createAnchor(string,string,uint8)"(
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
